title: Ritabrata Sanyal # your name (or website title) here
logo: "/images/73041613_2577331098979971_8364312701446389760_n.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior year CS undergrad with research interests in Computer Vision, Pattern Recognition and Medical Image Processing
  <br></br>
  <a href="https://github.com/rtb7syl">View my Github Profile</a>
  

